# Factom Default Configuration
# This is the default configuration file for factomd
# The configuration is from a merge order of:
# This file -> custom config -> CLI options
server:
  network: "local"
  role: "full" # ["full", "light", "authority"]
  node_key_env: "" # factomd will use this env var to find your node key 
  port: 30333
  bootnodes: ""
  base_path: ""

rpc:
  disable_rpc: false
  rpc_port: 8088
  rpc_addr: "127.0.0.1"

log:
  log_level: "DEBUG" # ["OFF", "CRITICAL", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"] in that order of precedence
  log_path: "factomd-logs.log"

walletd:
  walletd_user: ""
  walletd_env_var: "" # factomd will use this environment variable to determine walletd password 